title: charagarlnad
show_excerpts: true
baseurl:
url: https://charagarlnad.github.io

paginate: 5
paginate_path: "/blog/page:num/"

dash:
  date_format: "%b %-d, %Y"

  social_links:
    - url: https://twitter.com/charagarlnad
      icon: twitter
      color: cyan
    - url: https://github.com/charagarlnad
      icon: github
      color: purple
    - url: https://discord.gg/FJetFBe
      icon: discord
      color: indigo

remote_theme: bitbrain/jekyll-dash
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
